onlyBuiltDependencies:
  - esbuild
  - sharp

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@vpmedia/phixify'

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 1440
blockExoticSubdeps: true
